<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\{Country , City , County};

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $ugandaId = Country::where('country_name' ,'Like' ,  '%Uganda%')->first()->id;

        $data = [
            [
                'city' => 'Kampala',
                'towns' => [
                            'Nakasero',
                            'Kibuli',
                            'Kampala Central',
                            'Old Kampala',
                            'Kololo',
                            'Nakivubo',
                            'Bwaise',
                            'Kawempe',
                            'Kalerwe',
                            'Mpererwe',
                            'Kanyanya',
                            'Kiganda',
                            'Kansanga',
                            'Kabalagala',
                            'Lukuli',
                            'Kibuye',
                            'Ggaba',
                            'Nsambya',
                            'Bugolobi',
                            'Ntinda',
                            'Naguru',
                            'Mbuya',
                            'Kireka',
                            'Kyambogo',
                            'Nateete',
                            'Rubaga',
                            'Kasubi',
                            'Namirembe',
                            'Lubaga',
                            'Nakulabye'
                        ],
            ],
            [
                'city' => 'Fort Portal',
                'towns' => [
                            'Kagote',
                            'Kachwamba',
                            'Kitumba',
                            'Kisenyi',
                            'Boma',
                            'Kagote',
                            'Mugusu',
                            'Buhinga',
                            'Kasusu',
                            'Rwengoma',
                            'Kitarasa',
                            'Karago',
                            'Nyabukara',
                            'Rwengoma',
                            'Rwengoma',
                            'Kabarole',
                            'Karambi',
                            'Kicwamba',
                            'Rugombe',
                            'Iruhura',
                            'Kijura',
                            ],
            ],
            [
                'city' => 'Arua',
                'towns' => [
                            'Arua Hill',
                            'Tanganyika',
                            'Awindiri',
                            'Bazaar',
                            'Oli',
                            'Kampala Road',
                            'Anyafio',
                            'Mvara',
                            'River Oli',
                            'Adumi',
                            'Oluko',
                            'Arua Park',
                            'Vurra',
                            'Onduparaka',
                            'Oliya',
                            'Ajia',
                            'Ayivu',
                            'Obolokofuku',
                            'Ombaci',
                            'Aroi'
                        ],
            ],
            [
                'city' => 'Gulu',
                'towns' => [
                    'Pece',
                    'Layibi',
                    'Bardege',
                    'Senior Quarters',
                    'Lacor',
                    'Laroo',
                    'Unyama',
                    'Pabbo',
                    'Lacor',
                    'Cereleno',
                    'Odek',
                    'Bardege',
                    'Awach',
                    'Ker Kwaro Acholi',
                    'Lacor',
                    'Senior Quarters',
                    'Jal Kalaa',
                    'Pece',
                    'Senior Quarters',
                    'Layibi',
                    'Laroo',
                    'Cereleno',
                    'Unyama',
                            ],
            ],
            [
                'city' => 'Jinja',
                'towns' => [
                    'Main Street',
                    'Nile Avenue',
                    'Mpumudde',
                    'Wanyange',
                    'Nile Crescent',
                    'Wairaka',
                    'Bugembe',
                    'Mafubira',
                    'Mpumudde',
                    'Njeru',
                    'Kimaka',
                    'Buikwe',
                    'Nabugabo',
                    'Jinja Industrial Park',
                    'Nyenga Industrial Area',
                    'Kimaka Industrial Area',
                    'Njeru',
                    'Bugembe',
                    'Mafubira',
                    'Mpumudde',
                    'Nabitende',
                ],
            ],
            [
                'city' => 'Mbarara',
                'towns' => [
                    'Mbarara Central',
                    'Kamukuzi',
                    'Kakoba',
                    'Nyamitanga',
                    'Kakiika',
                    'Kashari',
                    'Kashari South',
                    'Kakoba',
                    'Rwampara',
                    'Kamukuzi',
                    'Nyamitanga',
                    'Kamukuzi',
                    'Biharwe',
                    'Boma',
                    'Nyamitanga',
                    'Kamukuzi'
                ],
            ],
            [
                'city' => 'Mbale',
                'towns' => [
                    'Mbale Central',
                    'Nkoma',
                    'Namakwekwe',
                    'Industrial Area',
                    'Northern Division',
                    'Nkoma',
                    'Bukasakya',
                    'Southern Division',
                    'Namakwekwe',
                    'Industrial Area',
                    'Bungokho Division',
                    'Makoma',
                    'Nauyo',
                    'Bukasakya',
                    'Nkoma',
                    'Namakwekwe'
                ],
            ],
            [
                'city' => 'Masaka',
                'towns' => [
                        'Masaka Central',
                        'Nyendo',
                        'Kitovu',
                        'Lukaya',
                        'Bukakata',
                        'Kimaanya',
                        'Buwalasi',
                        'Misanvu',
                        'Kitovu',
                        'Nabugabo',
                        'Kijjabwemi',
                        'Nyendo',
                        'Kimaanya',
                        'Katwe',
                        'Kimaanya-Kyabakuza'
                ],
            ],
            [
                'city' => 'Kampala',
                'towns' => [
                        'Nakasero',
                        'Kibuli',
                        'Kampala Central',
                        'Old Kampala',
                        'Kololo',
                        'Nakivubo',
                        'Bwaise',
                        'Kawempe',
                        'Kalerwe',
                        'Mpererwe',
                        'Kanyanya',
                        'Kiganda',
                        'Kansanga',
                        'Kabalagala',
                        'Lukuli',
                        'Kibuye',
                        'Ggaba',
                        'Nsambya',
                        'Bugolobi',
                        'Ntinda',
                        'Naguru',
                        'Mbuya',
                        'Kireka',
                        'Kyambogo',
                        'Nateete',
                        'Rubaga',
                        'Kasubi',
                        'Namirembe',
                        'Lubaga',
                        'Nakulabye'
                ],
            ],
            [
                'city' => 'Hoima',
                'towns' => [
                    'Hoima Central',
                    'Kahoora',
                    'Kibingo',
                    'Busiisi',
                    'Mparo',
                    'Bujumbura',
                    'Nyairongo',
                    'Kisiizi',
                    'Kagadi Road',
                    'Kasenene',
                    'Kahunge',
                    'Bugambe',
                    'Kabalega',
                    'Buhimba',
                    'Kabwooya',
                    'Kabwoya Wildlife Reserve',
                    'Katase',
                    'Kigorobya'
                            ],
            ],
            [
                'city' => 'Entebbe',
                'towns' => [
                    'Entebbe Central',
                    'Kitoro',
                    'Katabi',
                    'Nkumba',
                    'Kitubulu',
                    'Lweza',
                    'Namulanda',
                    'Nkumba',
                    'Nkumba University',
                    'Kitovu',
                    'Abaita Ababiri',
                    'Abayita Ababiri',
                    'Kigungu',
                    'Lweza',
                    'Nambigirwa'
                ],
            ],
            [
                'city' => 'Lira',
                'towns' => [
                    'Lira Central',
                    'Ojwina',
                    'Adyel',
                    'Ayere',
                    'Ojwina',
                    'Atek Okwerodot',
                    'Akwang',
                    'Amach',
                    'Adyel',
                    'Anywoli',
                    'Agweng',
                    'Amach',
                    'Orom',
                    'Abwoc',
                    'Acul',
                    'Adwari',
                    'Railway',
                    'Agoe',
                    'Anai',
                    'Adwari'
                ],
            ],
            [
                'city' => 'Kabale',
                'towns' => [
                    'Kabale Central',
                    'Rukore',
                    'Kamukira',
                    'Kakatunda',
                    'Kikungiri',
                    'Makanga',
                    'Nyakabungo',
                    'Kitumba',
                    'Mwanjari',
                    'Rwakibungo',
                    'Rukiga',
                    'Muhanga',
                    'Butanda',
                    'Kakore',
                    'Kabale Industrial Area',
                    'Kabale University Area'
                ],
            ],

            [
                'city' => 'Moroto',
                'towns' => [
                    'Moroto Central',
                    'Katanga',
                    'Rupa',
                    'Nadunget',
                    'Katanga',
                    'Loroo',
                    'Kapkoma',
                    'Nadunget',
                    'Rupa',
                    'Naitakwai',
                    'Nakiloro',
                    'Nadunget',
                    'Nakapelimen',
                    'Napak',
                    'Nabilatuk',
                    'Tapac',
                    'Nakapiripirit',
                    'Namalu'
                ],
            ],
            [
                'city' => 'Nakasongola',
                'towns' => [
                    'Nakasongola Central',
                    'Wabinyonyi',
                    'Ngoma',
                    'Kikamulo',
                    'Wabinyonyi',
                    'Kikamulo',
                    'Bombo',
                    'Bulwadda',
                    'Kikamulo',
                    'Bombo',
                    'Bulwadda',
                    'Nabiswera',
                    'Nakitoma',
                    'Nakitoma Central'
                ],
            ],

            [
                'city' => 'Wakiso',
                'towns' => [
                    'Kira Town',
                    'Kira Municipality',
                    'Kira Division',
                    'Namugongo',
                    'Nansana Town',
                    'Nansana Municipality',
                    'Nansana Division',
                    'Yesu Amala',
                    'Entebbe Town',
                    'Entebbe Municipality',
                    'Entebbe Division',
                    'Kigungu',
                    'Matugga Town',
                    'Matugga Trading Center',
                    'Matugga Division',
                    'Wakiso',
                    'Bweyogerere Town',
                    'Bweyogerere Trading Center',
                    'Bweyogerere Division',
                    'Nambole',
                ],
            ],
            [
                'city' => 'Soroti',
                'towns' => [
                    'Soroti Central',
                    'Senior Quarters',
                    'Owino',
                    'Western Division',
                    'Eastern Division',
                    'Arwotcek',
                    'Amuria Road',
                    'Eastern Quarters',
                    'Western Division',
                    'Okwalinga',
                    'Soroti Airfield',
                    'University Quarters',
                    'Northern Division',
                    'Kakoro',
                    'Aloet',
                    'Railway Quarters',
                    'Southern Division',
                    'Asuret',
                    'Aloi',
                    'Wolomay'
                ],
            ],

        ];

        foreach($data as $cities){
            $city = City::create(['country_id' => $ugandaId ,  'name' => $cities['city']]);
            $townList =[];
            foreach($cities['towns'] as $town)
            {
                $townList[] = ['city_id' => $city->id , 'name' => $town ];
            }
            County::insert($townList);
        }



    }
}
